title: StudioLE Pano
theme: default
baseURL: http://example.org
disableKinds: ["home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
uglyURLs: false
SectionPagesMenu: main