version: '3.3'

services:
  nginx:
    container_name: pano
    image: nginx:1.17.8-alpine
    expose: 
      - "443"
    volumes:
      - ./public:/usr/share/nginx/html
    labels:
      domain: pano.studiole.uk
    restart: unless-stopped
    networks:
      - traefik
networks:
  traefik:
    external:
      name: traefik_web